services:
  freshrss-db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
      - MYSQL_DATABASE=freshrss
      - MYSQL_USER=${{ secrets.MYSQL_USER }}
      - MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
    expose:
      - 3306
  freshrss:
    depends_on:
      - freshrss-db
    image: freshrss/freshrss:1.21.0-alpine
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions 
    ports:
      - 8085:80
    restart: always
    logging:
      options:
        max-size: 10m
    environment:
      FRESHRSS_INSTALL: |-
        --api_enabled
        --db-base freshrss
        --db-host freshrss-db
        --db-password ${{ secrets.MYSQL_PASSWORD }}
        --db-type mysql 
        --db-user ${{ secrets.MYSQL_USER }}
        --default_user ${{ secrets.FRESHRSS_USER }}
        --language en
      FRESHRSS_USER: |-
        --api_password ${{ secrets.FRESHRSS_API_PASSWORD }}
        --email ${{ secrets.FRESHRSS_EMAIL }}
        --language en
        --password ${{ secrets.FRESHRSS_PASSWORD }}
        --user ${{ secrets.FRESHRSS_USER }} 
volumes:
 db_data:
 data: 
 extensions:
