name: remote into server
on: [push]
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~
          git clone git@github.com:pmoralesgarcia/freshrss-docker.git
          cd freshrss-docker
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          git pull
          docker compose up
        
  
