name: remote into server
on: [push]
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Load secret
      uses: 1password/load-secrets-action@v1
      with:
       # Export loaded secrets as environment variables
        export-env: true
      env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          USERNAME: op://production-server/username
          PRIVATE_SSH_KEY: "op://production-server/private key"
          SERVER_HOST: op://production-server/host
                    
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: $SERVER_HOST
        username: $USERNAME
        key: $PRIVATE_SSH_KEY
        port: 22
        script: |
          cd ~
          rm -rf freshrss-docker
          git clone git@github.com:pmoralesgarcia/freshrss-docker.git
          cd freshrss-docker
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          git pull
          MYSQL_USER=${{ secrets.MYSQL_USER }} \
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
          FRESHRSS_USER=${{ secrets.FRESHRSS_USER }} \
          FRESHRSS_EMAIL=${{ secrets.FRESHRSS_EMAIL }} \
          FRESHRSS_PASSWORD=${{ secrets.FRESHRSS_PASSWORD }} \
          FRESHRSS_API_PASSWORD=${{ secrets.FRESHRSS_API_PASSWORD }} \
          docker compose down
          MYSQL_USER=${{ secrets.MYSQL_USER }} \
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
          FRESHRSS_USER=${{ secrets.FRESHRSS_USER }} \
          FRESHRSS_EMAIL=${{ secrets.FRESHRSS_EMAIL }} \
          FRESHRSS_PASSWORD=${{ secrets.FRESHRSS_PASSWORD }} \
          FRESHRSS_API_PASSWORD=${{ secrets.FRESHRSS_API_PASSWORD }} \
          docker compose up --detach
        
  
